name = "XML2011"
uuid = "231fd75e-8d63-4bb9-bdb3-b45279e1fb06"
authors = ["lucasprocessi <lucasprocessi@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
